from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from io import BytesIO

def generate_pdf_report(audit_data):
    """
    Generates a professional Agency Brief PDF from the audit data.
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=LETTER)
    styles = getSampleStyleSheet()
    
    # Custom Styles
    title_style = ParagraphStyle(
        'AgencyTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#2E86C1'),
        spaceAfter=20
    )
    
    subtitle_style = ParagraphStyle(
        'AgencySubtitle',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.grey,
        spaceAfter=30
    )
    
    # Content Collection
    content = []
    
    # 1. HEADER
    content.append(Paragraph("AudiencePulse | Agency Brief", title_style))
    content.append(Paragraph(f"Creator Analysis: {audit_data.get('creator_name', 'Unknown')}", subtitle_style))
    content.append(Spacer(1, 12))
    
    # 2. EXECUTIVE SUMMARY (Score Card)
    score = audit_data.get('final_score', 0)
    grade = audit_data.get('analysis_json', {}).get('creator_fit', {}).get('grade', 'N/A')
    verdict = audit_data.get('analysis_json', {}).get('creator_fit', {}).get('verdict', 'No verdict')
    
    # Color logic
    score_color = colors.green if score > 75 else (colors.orange if score > 50 else colors.red)
    
    summary_data = [
        ['Overall Fit Score', 'Grade', 'Recommendation'],
        [f"{score}/100", grade, verdict]
    ]
    
    t = Table(summary_data, colWidths=[150, 100, 250])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f0f2f6')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.navy),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.white),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('TEXTCOLOR', (0, 1), (0, 1), score_color), # Color the score
        ('FONTSIZE', (0, 1), (-1, -1), 14),
    ]))
    content.append(t)
    content.append(Spacer(1, 30))
    
    # 3. CAMPAIGN CONTEXT
    campaign_style = ParagraphStyle('Body', parent=styles['BodyText'], spaceAfter=10)
    content.append(Paragraph("Campaign Context", styles['Heading2']))
    
    product_name = audit_data.get('product_name', 'N/A')
    tier = audit_data.get('price_tier', 'N/A')
    
    content.append(Paragraph(f"<b>Product:</b> {product_name}", campaign_style))
    content.append(Paragraph(f"<b>Budget Tier:</b> {tier}", campaign_style))
    content.append(Spacer(1, 20))

    # 4. AUDIENCE DNA
    content.append(Paragraph("Audience Intelligence", styles['Heading2']))
    
    dna = audit_data.get('analysis_json', {}).get('audience_dna', {})
    persona = dna.get('dominant_persona', 'Unknown')
    sentiment = dna.get('sentiment', {}).get('positive', 0)
    
    content.append(Paragraph(f"<b>Dominant Persona:</b> {persona}", campaign_style))
    content.append(Paragraph(f"<b>Audience Sentiment:</b> {sentiment}% Positive", campaign_style))
    
    # 5. DISCLAIMER
    content.append(Spacer(1, 50))
    disclaimer_style = ParagraphStyle('Disclaimer', parent=styles['Normal'], fontSize=8, textColor=colors.grey)
    content.append(Paragraph("Generated by AudiencePulse AI. Confidential Agency Use Only.", disclaimer_style))
    
    # Build
    doc.build(content)
    buffer.seek(0)
    return buffer

