apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: audiencepulse-secrets-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "e5f6b34f-4eee-47e7-ac12-e545071c3619" # AKS kubelet identity
    keyvaultName: "kvshrinet82prod"
    tenantId: "0cd5a9c5-e95c-49b1-aa42-e56c1fdfeab9"
    objects: |
      array:
        - |
          objectName: GROQ-API-KEY
          objectType: secret
  secretObjects:
    - secretName: audiencepulse-secrets
      type: Opaque
      data:
        - objectName: GROQ-API-KEY
          key: GROQ_API_KEY
